# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e9ed49eacc09e55ea8dd990a09722cdafc9c4df7226613124143888fc7fa6cff21df3f3b8c7ed10285de70ce3c04497e63f095bda8df9bdbba1abeb619c0dad

test:
  secret_key_base: dcc10327a89232d28a21ba7ef23466e7375c5b447609c307840edf4f1e9ed1b03b33d996e297edf5cb7e00e614e640ac5f4df209217734e82fe7dc2cc8bbabbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
